# Generated by Django 3.1.2 on 2025-09-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
