# Generated by Django 3.1.2 on 2025-02-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cert_id',
            field=models.CharField(default='dfdfff', max_length=255),
            preserve_default=False,
        ),
    ]
