# Generated by Django 3.1.2 on 2025-02-10 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_cert_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AddField(
            model_name='document',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='issued_by',
            field=models.CharField(default='inspector Africa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='recipient_name',
            field=models.CharField(default='masud', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='cert_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='ipfs_cid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
