# Generated by Django 3.1.2 on 2025-02-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20250210_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='duration_valid',
            field=models.IntegerField(default=0),
        ),
    ]
