# Generated by Django 3.1.2 on 2025-02-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_duration_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='blockchain_tx_hash',
        ),
        migrations.AddField(
            model_name='document',
            name='ipfsUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='ipfs_cid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
